export const GET_INSTRUCTORS = 'GET_INSTRUCTORS';
export const SET_INSTRUCTORS = 'SET_INSTRUCTORS';

export const CREATE_INSTRUCTOR = 'CREATE_INSTRUCTOR';
export const DELETE_INSTRUCTOR = 'DELETE_INSTRUCTOR';
